title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: https://piazzai.github.io/jekyll-nagymaros

theme: jekyll-nagymaros

copyright: Place Holder
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
