title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: https://umr-summer-school.github.io/UMR_Summer_School/

theme: jekyll-nagymaros

copyright: false
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
